name: IcePee
nextSceneId: 6
selectedScene: 1
canvasWidth: 1280
canvasHeight: 720
scalingMode: fitwidth
textureStrategy: resize
luaDir: .
terrainEditor:
  brushMode: 0
  brushShape: 0
  brushFalloff: 0
  brushSize: 4
  brushStrength: 0.04
  flattenHeight: 0.5
  heightMapResolution: 512
  blendMapResolution: 512
  normalizeBlendPaint: true
  heightMapStartAtMiddle: true
tabs:
  - type: codeeditor
    filepath: IcePee.h
  - type: codeeditor
    filepath: IcePee.cpp
  - type: scene
    filepath: models/New Scene 5.scene
  - type: scene
    filepath: assets/New Scene 6.scene
  - type: codeeditor
    filepath: ButtonScript.h
  - type: scene
    filepath: Main Scene.scene
scenes:
  - filepath: Main Scene.scene
    showAllJoints: false
    showAllBones: false
    showAllBodies: false
    hideCameraView: false
    hideLightIcons: false
    hideSoundIcons: false
    hideContainerGuides: false
    showOrigin: true
    showGrid3D: true
    hideSelectionOutline: false
    showGrid2D: false
    gridSpacing2D: 50
    gridSpacing3D: 1
    snapToGrid: false
    snapRotation: false
    rotationSnapDegrees: 15
    editorCamera:
      type: camera_perspective
      target: [1.1674706, 0.49569443, -0.35838825]
      up: [0, 1, 0]
      yfov: 0.75
      aspect: 2.512431
      nearClip: 0.2
      farClip: 200
      position: [7.861709, 3.990472, 8.39712]
  - filepath: UI Scene.scene
    showAllJoints: false
    showAllBones: false
    showAllBodies: false
    hideCameraView: false
    hideLightIcons: false
    hideSoundIcons: false
    hideContainerGuides: false
    showOrigin: true
    showGrid3D: true
    hideSelectionOutline: false
    showGrid2D: false
    gridSpacing2D: 50
    gridSpacing3D: 1
    snapToGrid: false
    snapRotation: false
    rotationSnapDegrees: 15
    editorCamera:
      type: camera_ui
      target: [-726.739, -140.4632, 0]
      up: [0, 1, 0]
      yfov: 0.75
      aspect: 1.6367265
      nearClip: -10000
      farClip: 10000
      position: [-726.739, -140.4632, 1]
      zoom: 1.4641001